version: 2

updates:

# Run dependabot only for the development Python requirements (under `/.dev` folder)
- package-ecosystem: pip
  directory: "/.dev"
  schedule:
    interval: weekly
    day: monday
    time: "05:18"
  target-branch: master
  labels:
    - CI/CD
    - skip-changelog
  groups:
    packages:
      applies-to: version-updates
      patterns: ["*"]
    security:
      applies-to: security-updates
      patterns: ["*"]

# Run dependabot for all GitHub Actions
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: master
  labels:
    - CI/CD
    - skip-changelog
