version: 2

updates:

# Run dependabot only for the development Python requirements (under `/.dev` folder)
- package-ecosystem: pip
  directory: "/.dev"
  schedule:
    interval: weekly
    day: monday
    time: "05:18"
  # Should be bigger than or equal to the total number of dependencies (currently 5)
  open-pull-requests-limit: 10
  target-branch: ci/dependabot-updates
  labels:
    - CI/CD

# Run dependabot for all GitHub Actions
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "05:24"
  target-branch: ci/dependabot-updates
  labels:
    - CI/CD
