# pre-commit.ci
ci:
  autofix_commit_msg: |
      [pre-commit.ci] auto fixes from pre-commit hooks

      For more information, see https://pre-commit.ci
  autofix_prs: false
  autoupdate_branch: 'main'
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: 'weekly'
  skip: [pylint, pylint-tests]
  submodules: false

# hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-yaml
      name: Check YAML
    - id: check-toml
      name: Check TOML
    - id: requirements-txt-fixer
      name: Fix requirements*.txt
      files: ^requirements.*\.txt$
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files", "--skip-gitignore"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    - id: pyupgrade
      args: ["--py39-plus"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
    - id: bandit
      args: ["-r"]
      files: ^app/.*$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
    - id: mypy
      exclude: ^tests/.*$
      additional_dependencies:
        - "types-requests"
        - "pydantic>=2,<3"
        - "types-redis"

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      args: ["--rcfile=pyproject.toml", "--extension-pkg-whitelist='pydantic'"]
      language: python
      types: [python]
      require_serial: true
      files: ^.*$
      exclude: ^tests/.*$
    - id: pylint-tests
      name: pylint - tests
      entry: pylint
      args: ["--rcfile=pyproject.toml", "--extension-pkg-whitelist='pydantic'", "--disable=C0415,W0621,E1101"]
      language: python
      types: [python]
      require_serial: true
      files: ^tests/.*$
