version: '3'

scanning-settings:
  exclude:
    - '.github/**'
  include-files:
    - path: .dev/requirements_ci.txt
      file-type: requirements.txt
    - path: .dev/requirements_dev.txt
      file-type: requirements.txt
    - path: .dev/requirements_release.txt
      file-type: requirements.txt
