version: '3.0'

scanning-settings:
  exclude:
    - '.github/**'
  include-files:
    - path: .dev/requirements_ci.txt
      type: requirements.txt
    - path: .dev/requirements_dev.txt
      type: requirements.txt
    - path: .dev/requirements_release.txt
      type: requirements.txt
