[tool.pylint]
disable = ["duplicate-code"]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
scripts_are_modules = true
warn_unused_configs = true
show_error_codes = true
allow_redefinition = true
plugins = ["pydantic.mypy"]

[tool.pytest.ini_options]
addopts = "-rs --cov=app --cov-report=term-missing"
filterwarnings = [
    "ignore:.*imp module.*:DeprecationWarning",

]
