version: "3.3"

services:
  oteapi:
    build:
      context: "../../"
      target: "${DOCKER_OTEAPI_TARGET:-development}"
    ports:
      - "${PORT:-8080}:8080"
      - "5678:5678" # Debug port
    environment:
      OTEAPI_REDIS_TYPE: redis
      OTEAPI_REDIS_HOST: redis
      OTEAPI_REDIS_PORT: 6379
      OTEAPI_prefix: "${OTEAPI_prefix:-/api/v1}"
      OTEAPI_INCLUDE_REDISADMIN: "${OTEAPI_INCLUDE_REDISADMIN:-True}"
      OTEAPI_EXPOSE_SECRETS: "${OTEAPI_EXPOSE_SECRETS:-True}"
      PATH_TO_OTEAPI_CORE: "${PATH_TO_OTEAPI_CORE:-/dev/null}"
      OTEAPI_PLUGIN_PACKAGES:
      OTEAPI_AUTHENTICATION_DEPENDENCIES:
      CI:
    depends_on:
      - redis
    networks:
      - otenet
    volumes:
      - "${LOCAL_TARGET_PLUGIN_PATH:-/dev/null}:${CONTAINER_PLUGIN_PATH:-/dev/null}"
      - "${PATH_TO_OTEAPI_CORE:-/dev/null}:/oteapi_core"

  redis:
    image: redis:latest
    volumes:
      - redis-persist:/data
    networks:
      - otenet

volumes:
  redis-persist:

networks:
  otenet:
